---
version: "3.4"

services:
  api:
    image: netnitel
    container_name: netnitel
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - TZ=Europe/Paris
    ports:
      - "3615:3615"
